"""What happens when someone imports THAT.

The fixtures in `tests/fixtures/merge/` are generated by
`tools/make_test_networks.py` and split into files that must import and files
that must be refused. This pins which is which, and — for the refusals — that
the message names the thing that is wrong. A refusal nobody can act on is only
marginally better than a crash.
"""
from __future__ import annotations

import os

import pytest

from bikenetwork.network_format import parse_network, validate_network

HERE = os.path.dirname(__file__)
FIXTURES = os.path.join(HERE, "fixtures", "merge")


def load(name: str):
    with open(os.path.join(FIXTURES, name), encoding="utf-8") as fh:
        return parse_network(fh.read())


IMPORTABLE = ["absurd-but-valid.yaml", "adversarial.yaml"]

# name -> a phrase the error has to contain, so the user knows what to fix.
REFUSED = {
    "adversarial-rejected.yaml": "loop",
    "bad-references.yaml": "upgrade itself",
    "id-collision.yaml": "duplicate id",
    "invalid-bad-units.yaml": "units",
    "invalid-future-version.yaml": "newer than this tool",
    "invalid-geometry-types.yaml": "[lat, lon]",
    "invalid-wrong-format.yaml": "unrecognized format",
}

UNPARSEABLE = {
    "invalid-not-yaml.yaml": None,
    "invalid-truncated.yaml": None,
    "invalid-empty.yaml": "doesn't look like a bike network",
}


@pytest.mark.parametrize("name", IMPORTABLE)
def test_strange_but_legal_files_import(name):
    net = load(name)
    assert validate_network(net) == [], f"{name} should import cleanly"
    assert net.features, f"{name} should carry features"


@pytest.mark.parametrize("name,phrase", sorted(REFUSED.items()))
def test_invalid_files_are_refused_with_a_usable_message(name, phrase):
    errors = validate_network(load(name))
    assert errors, f"{name} should NOT validate"
    joined = " ".join(errors).lower()
    assert phrase.lower() in joined, f"{name}: {phrase!r} not in {errors}"


@pytest.mark.parametrize("name,phrase", sorted(UNPARSEABLE.items()))
def test_unparseable_files_raise_rather_than_pretending(name, phrase):
    with open(os.path.join(FIXTURES, name), encoding="utf-8") as fh:
        text = fh.read()
    with pytest.raises(Exception) as caught:
        parse_network(text)
    if phrase:
        assert phrase in str(caught.value)


def test_an_empty_file_is_not_an_empty_network():
    """The gap these fixtures were written to find.

    An empty document used to parse into a default Network that validated
    clean, so importing an empty or unrelated file reported SUCCESS — and on an
    empty map that replaced the network with nothing.
    """
    for text in ("", "\n\n", "# just a comment\n", "some_other_tool: true\n"):
        with pytest.raises(ValueError, match="look like a bike network"):
            parse_network(text)


def test_a_counted_treatment_on_a_line_is_legal_in_the_format():
    """The speed-hump corridor.

    The registry says speed humps are point-only and the editor will not offer
    one on a line. The FORMAT allows it anyway, and must keep doing so: a file
    written by another tool is not wrong for saying something we would not.
    """
    net = load("absurd-but-valid.yaml")
    humps = next(f for f in net.features if f.id == "f-humps")
    assert humps.treatments[0].type == "speed_hump"
    assert len(humps.geometry[0]) >= 2, "on a LINE, not a point"
    assert validate_network(net) == []
