// Tests for boundary clipping — mirrors tests/test_boundary.py, except the
// polygon arrives as a precomputed ring (web/data/malden_boundary_polygon.json,
// generated by tools/export_boundary_polygon.py) instead of being polygonized
// from raw ways at runtime.
import test from "node:test";
import assert from "node:assert/strict";
import {
  pointInRing, clipPolylineLatlon, clipSegmentsLatlon,
} from "../js/boundary.js";

// A unit square ring in (lat, lon): lat in [0,1], lon in [0,1].
const SQUARE = [[0.0, 0.0], [0.0, 1.0], [1.0, 1.0], [1.0, 0.0], [0.0, 0.0]];

test("point in ring: interior and exterior", () => {
  assert.ok(pointInRing(0.5, 0.5, SQUARE));
  assert.ok(!pointInRing(2.0, 2.0, SQUARE));
});

test("clip keeps inside portion", () => {
  // Horizontal line at lat=0.5, lon from -0.5 (outside) to 0.5 (inside).
  const [clipped, miles] = clipPolylineLatlon([[0.5, -0.5], [0.5, 0.5]], SQUARE);
  const lons = clipped.map(([, lon]) => lon);
  assert.ok(Math.min(...lons) >= -1e-9);
  assert.ok(Math.abs(Math.max(...lons) - 0.5) < 1e-9);
  assert.ok(miles > 0);
});

test("clip fully outside returns empty", () => {
  const [clipped, miles] = clipPolylineLatlon([[5.0, 5.0], [6.0, 6.0]], SQUARE);
  assert.deepEqual(clipped, []);
  assert.equal(miles, 0.0);
});

test("clip fully inside unchanged length", () => {
  const [clipped, miles] = clipPolylineLatlon([[0.5, 0.2], [0.5, 0.8]], SQUARE);
  assert.ok(clipped.length >= 2);
  assert.ok(miles > 0);
});

test("clip keeps the longest piece when the line leaves and re-enters", () => {
  // In at lon 0..0.2 (short), out over the notchless square? A concave case:
  // cross the square fully, leave, and come back — the longer inside run wins.
  const line = [[0.5, -0.2], [0.5, 0.1],   // short inside piece (0 .. 0.1)
                [1.5, 0.1],                 // exits north
                [1.5, 0.9], [0.5, 0.9], [0.5, 0.3]]; // long inside piece
  const [clipped, miles] = clipPolylineLatlon(line, SQUARE);
  assert.ok(miles > 0);
  // The kept piece is the re-entry run (lon spans ~0.9 down to 0.3).
  const lons = clipped.map(([, lon]) => lon);
  assert.ok(Math.max(...lons) > 0.8);
});

test("clip segments drops fully-outside segments and totals miles", () => {
  const segments = [
    [[0.5, 0.2], [0.5, 0.8]],       // inside
    [[5.0, 5.0], [6.0, 6.0]],       // outside — dropped
  ];
  const [kept, total] = clipSegmentsLatlon(segments, SQUARE);
  assert.equal(kept.length, 1);
  assert.ok(total > 0);
});
