#!/usr/bin/env python3
"""Generate the awkward network files used to exercise import and merge.

    python tools/make_test_networks.py

Writes into `tests/fixtures/merge/`. These exist so that "what happens if
someone imports THAT" is a question with an answer you can click on, rather
than a thing you find out from a bug report. Three kinds:

* **valid but strange** — legal v2 that says something nobody would build. A
  corridor of speed humps, a feature with forty treatments, coordinates in the
  Southern Ocean. The FORMAT allows these; the point is that the tool should
  survive them and say something sensible.
* **adversarial** — legal-ish files built to break assumptions: ids that
  collide across namespaces, upgrade chains that loop, geometry with one point,
  names that are only whitespace, numbers where strings belong.
* **invalid** — files that must be REFUSED with a readable message, because
  nothing stops someone hand-editing a file or a download truncating.

Regenerate after changing the format. The files are committed so the JS suite
can read them without running Python.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

OUT = ROOT / "tests" / "fixtures" / "merge"

# A small square around Malden, so these overlay the real network usefully.
BOX = [[42.42, -71.08], [42.44, -71.08], [42.44, -71.05], [42.42, -71.05],
       [42.42, -71.08]]


def line(a, b):
    return [[list(a), list(b)]]


HEAD = """# Generated by tools/make_test_networks.py — do not hand-edit.
# {why}
format: bike-network
format_version: 2
crs: EPSG:4326
units: metric
"""


def area_block(id_="a-malden", name="Malden", boundary=True):
    out = ["areas:", f"  - id: {id_}", f"    name: {name}",
           "    kind: municipality", "    context: Massachusetts"]
    if boundary:
        out.append("    boundary:")
        out.append("      - - " + "\n          - ".join(
            f"- {lat}\n            - {lon}" for lat, lon in BOX))
    return "\n".join(out) + "\n"


def write(name: str, text: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(text, encoding="utf-8", newline="\n")
    print(f"  {name:34} {len(text):6} bytes")


# ---------------------------------------------------------------------------
# Valid, but nobody would build it
# ---------------------------------------------------------------------------

def absurd_but_valid() -> str:
    """The speed-hump corridor, and friends.

    The registry says speed humps are point-only and the editor will not offer
    one on a line — but the FORMAT allows any treatment on any geometry and
    always will, because a file written by another tool is not wrong for saying
    so. This is what that looks like.
    """
    feats = []
    feats.append(f"""  - id: f-humps
    name: The Endless Speed Hump Corridor
    on_street: Anywhere Street
    notes: >-
      2.4 km of continuous speed humps. Valid YAML, valid v2, and a war crime.
      Here to prove the editor renders a counted treatment on a line as a run
      of glyphs instead of pretending it is a bike lane.
    geometry: {line([42.425, -71.078], [42.437, -71.055])}
    treatments:
      - {{id: t-humps, type: speed_hump, status: proposed, phase: p1,
         quantity: 240}}""")
    feats.append(f"""  - id: f-parking-line
    name: Bike Parking, But As A Road
    geometry: {line([42.428, -71.070], [42.432, -71.062])}
    treatments:
      - {{id: t-parking-line, type: bike_parking, status: existing, quantity: 8}}""")
    stack = "\n".join(
        f"      - {{id: t-stack-{i}, type: {t}, status: proposed, phase: p1}}"
        for i, t in enumerate(
            ["quick_build_separated", "concrete_separated", "shared_use_path",
             "buffered_painted", "neighborway", "pedestrianized",
             "street_trees", "bollards", "parking_removal", "other"], start=1))
    feats.append(f"""  - id: f-everything
    name: Every Treatment At Once
    notes: Ten treatments on one line. The map draws the top-ranked few.
    geometry: {line([42.423, -71.075], [42.441, -71.058])}
    treatments:
{stack}""")
    feats.append("""  - id: f-antarctic
    name: Somewhere Else Entirely
    notes: Valid coordinates, nowhere near the area. Must not be counted.
    geometry: [[[-64.5, -63.5], [-64.6, -63.4]]]
    treatments:
      - {id: t-antarctic, type: shared_use_path, status: existing}""")
    feats.append("""  - id: f-onepoint
    name: A Spot Pretending To Be Nothing
    geometry: [[[42.430, -71.066]]]
    treatments:
      - {id: t-onepoint, type: hawk_signal, status: funded, quantity: 1}""")
    return (HEAD.format(why="Valid v2 that says absurd things. Must IMPORT.")
            + area_block()
            + "authorities:\n  - {id: local, name: City of Malden, level: municipal}\n"
            + "phases:\n  - {id: p1, number: 1, label: Someday}\n"
            + "features:\n" + "\n".join(feats) + "\n")


# ---------------------------------------------------------------------------
# Adversarial
# ---------------------------------------------------------------------------

def adversarial() -> str:
    """Weird but LEGAL. Must import, and then behave sanely once inside."""
    return (HEAD.format(why="Hostile but importable. Must not crash the tool.")
            + area_block(id_="shared-id")
            + """authorities:
  - {id: local, name: "  ", level: municipal}
phases:
  - {id: p1, number: 1, label: "Phase \\u00a0"}
  - {id: p2, number: 1, label: Also Phase One}
features:
  - id: f-unicode
    name: "R\\u00fce de la \\u00c9toile \\U0001F6B2 \\u2014 \\u00abtest\\u00bb"
    on_street: "\\u0627\\u0644\\u0634\\u0627\\u0631\\u0639"
    notes: "Right-to-left, emoji, and a non-breaking space walk into a bar."
    geometry: [[[42.4255, -71.0771], [42.4361, -71.0552]]]
    treatments:
      - {id: t-unicode, type: quick_build_separated, status: proposed, phase: p1}
  - id: f-blank-name
    name: "\u00a0 . \u00a0"
    notes: A name that is very nearly nothing, but survives the required check.
    geometry: [[[42.4262, -71.0740], [42.4340, -71.0600]]]
    treatments:
      - {id: t-blank, type: neighborway, status: proposed, phase: p2}
  - id: f-huge
    name: A Corridor Around The World
    notes: Legal coordinates, absurd extent. Length maths must not overflow.
    geometry: [[[89.9, -179.9], [-89.9, 179.9]]]
    treatments:
      - {id: t-huge, type: shared_use_path, status: proposed, phase: p1}
  - id: f-zero-length
    name: Start Equals End
    geometry: [[[42.4300, -71.0660], [42.4300, -71.0660]]]
    treatments:
      - {id: t-zero, type: quick_build_separated, status: proposed, phase: p1}
  - id: f-unknown-type
    name: Teleporter Lane
    notes: An unknown treatment type. Lenient vocabulary — a notice, not an error.
    geometry: [[[42.4280, -71.0690], [42.4360, -71.0570]]]
    treatments:
      - {id: t-unknown, type: antigravity_corridor, status: proposed, phase: p1}
""")


def adversarial_rejected() -> str:
    """The bits of the adversarial file that structure says no to.

    An upgrade loop and a negative count are not matters of taste: one makes
    the phase view unresolvable and the other makes the arithmetic lie.
    """
    return (HEAD.format(why="Hostile AND invalid. Must be REFUSED, readably.")
            + area_block()
            + """authorities:
  - {id: local, name: City of Malden, level: municipal}
phases:
  - {id: p1, number: 1, label: Now}
features:
  - id: f-upgrade-loop\n    name: The Upgrade That Upgrades Itself\n    notes: t-loop-a replaces t-loop-b, which replaces t-loop-a.\n    geometry: [[[42.4290, -71.0700], [42.4330, -71.0630]]]\n    treatments:\n      - {id: t-loop-a, type: buffered_painted, status: existing,\n         upgrades: [t-loop-b]}\n      - {id: t-loop-b, type: concrete_separated, status: proposed, phase: p1,\n         upgrades: [t-loop-a]}\n  - id: f-negative\n    name: Minus Eight Bike Racks\n    geometry: [[[42.4320, -71.0640]]]\n    treatments:\n      - {id: t-negative, type: bike_parking, status: existing, quantity: -8}\n""")


def bad_references() -> str:
    """Upgrades and phases that point at nothing, and a treatment that upgrades
    itself. Structure is strict, so all of these must be REFUSED — but each
    message has to name the thing that is wrong."""
    return (HEAD.format(why="Broken references. Must be REFUSED, readably.")
            + area_block()
            + """authorities:
  - {id: local, name: City of Malden, level: municipal}
phases:
  - {id: p1, number: 1, label: Now}
features:
  - id: f-self-upgrade
    name: Ouroboros Lane
    geometry: [[[42.4300, -71.0680], [42.4310, -71.0660]]]
    treatments:
      - {id: t-self, type: shared_use_path, status: proposed, phase: p1,
         upgrades: [t-self]}
  - id: f-dangling-refs
    name: Points At Nothing
    notes: An authority, a phase and an upgrade target that do not exist.
    geometry: [[[42.4270, -71.0720], [42.4350, -71.0580]]]
    treatments:
      - {id: t-dangling, type: pedestrianized, status: proposed,
         phase: p-nope, authority: ministry-of-silly-walks,
         upgrades: [t-does-not-exist]}
  - id: f-no-name
    geometry: [[[42.4262, -71.0740], [42.4340, -71.0600]]]
    treatments:
      - {id: t-no-name, type: neighborway, status: proposed, phase: p1}
  - id: f-unphased
    name: Proposed With No Phase
    geometry: [[[42.4250, -71.0760], [42.4350, -71.0560]]]
    treatments:
      - {id: t-unphased, type: quick_build_separated, status: proposed}
""")


def id_collision() -> str:
    """One id used for an area, a phase, a feature AND a treatment.

    They share one namespace, so this must be REFUSED — but it has to be
    refused with a message that names the id.
    """
    return (HEAD.format(why="Every namespace reusing one id. Must be REFUSED.")
            + area_block(id_="dup")
            + """authorities:
  - {id: dup, name: Also Dup, level: municipal}
phases:
  - {id: dup, number: 1, label: Dup Again}
features:
  - id: dup
    name: Still Dup
    geometry: [[[42.4300, -71.0700], [42.4340, -71.0620]]]
    treatments:
      - {id: dup, type: quick_build_separated, status: proposed, phase: dup}
""")


# ---------------------------------------------------------------------------
# Invalid — must be refused, readably
# ---------------------------------------------------------------------------

INVALID = {
    "invalid-not-yaml.yaml": (
        "# Must be REFUSED: not YAML at all.\n"
        "format: bike-network\n"
        "features:\n"
        "  - id: f1\n"
        "    name: [unclosed\n"
        "    geometry: {{{\n"),
    "invalid-truncated.yaml": (
        "# Must be REFUSED: a download that stopped halfway.\n"
        "format: bike-network\n"
        "format_version: 2\n"
        "units: metric\n"
        "features:\n"
        "  - id: f-cut\n"
        "    name: Half A Corridor\n"
        "    geometry: [[[42.43, -71.07], [42.44,\n"),
    "invalid-wrong-format.yaml": (
        "# Must be REFUSED: a different tool's file that happens to be YAML.\n"
        "format: transit-network\n"
        "format_version: 2\n"
        "units: metric\n"
        "features: []\n"),
    "invalid-future-version.yaml": (
        "# Must be REFUSED: written by a newer tool than this one.\n"
        "format: bike-network\n"
        "format_version: 99\n"
        "units: metric\n"
        "features: []\n"),
    "invalid-bad-units.yaml": (
        "# Must be REFUSED: units is not a display preference in the file.\n"
        "format: bike-network\n"
        "format_version: 2\n"
        "units: furlongs\n"
        "features: []\n"),
    "invalid-geometry-types.yaml": (
        "# Must be REFUSED: strings where coordinates belong.\n"
        "format: bike-network\n"
        "format_version: 2\n"
        "units: metric\n"
        "features:\n"
        "  - id: f-strings\n"
        "    name: Coordinates As Prose\n"
        "    geometry: [[[\"forty-two\", \"minus seventy-one\"]]]\n"
        "    treatments:\n"
        "      - {id: t-strings, type: shared_use_path, status: existing}\n"),
    "invalid-empty.yaml": (
        "# Must be REFUSED: an empty file.\n"),
}


def main() -> int:
    print(f"writing to {OUT}")
    write("absurd-but-valid.yaml", absurd_but_valid())
    write("adversarial.yaml", adversarial())
    write("adversarial-rejected.yaml", adversarial_rejected())
    write("bad-references.yaml", bad_references())
    write("id-collision.yaml", id_collision())
    for name, text in INVALID.items():
        write(name, text)
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
